image: continuumio/anaconda3:2021.05
stages:
  - check-files
  - lint
  - run

check-lab-files:
  tags:
    - docker
  stage: check-files
  script:
    - test -f .gitignore
    - test -f .pylintrc
    - test -f common/classification_metrics.py
    - test -f common/describe_data.py
    - test -f common/test_env.py
    - test -f lab3.py
    - find . -name "*" -not -path "./.git/*" -not -path "./builds/*" 2>&1

lint-lab:
  tags:
    - docker
  stage: lint
  script:
    # Check formatting
    - autopep8 -d --exit-code lab3.py
    # Lint
    - pylint lab3.py

run-lab:
  tags:
    - docker
  stage: run
  script:
    - chmod +x lab3.py
    - ./lab3.py
  artifacts:
    name: lab3-results-$CI_COMMIT_SHORT_SHA
    paths:
      - results/
